spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/music?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver